application: bozemanpolicereports-hrd
version: 5
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /rss
  script: rss.py
- url: /rss/.*
  script: rss.py
- url: /refresh/.*
  script: index.py
